use anyhow::Result;
use axum::Router;

use crate::Container;

/*
ControllerBasePath = metadata implemented by #[controller("/...")]
*/
pub trait ControllerBasePath {
    fn base_path() -> &'static str;
}

/*
ControllerDefinition = generated by #[routes] for a controller
*/
pub trait ControllerDefinition: Send + Sync + 'static {
    fn router() -> Router<Container>;
}

/*
ModuleDefinition = app module contract (manual for now)
*/
pub trait ModuleDefinition: Send + Sync + 'static {
    fn register(container: &Container) -> Result<()>;

    fn controllers() -> Vec<Router<Container>> {
        Vec::new()
    }
}