use anyhow::Result;
use axum::Router;
use std::collections::HashSet;

use crate::{framework_log_event, Container, RouteDocumentation};

pub type LifecycleHook = fn(&Container) -> Result<()>;

/*
ControllerBasePath = metadata implemented by #[controller("/...")]
*/
pub trait ControllerBasePath {
    fn base_path() -> &'static str;
}

/*
ControllerDefinition = generated by #[routes] for a controller
*/
pub trait ControllerDefinition: Send + Sync + 'static {
    fn router() -> Router<Container>;
}

#[derive(Clone, Copy)]
pub struct ModuleRef {
    pub name: &'static str,
    pub register: fn(&Container) -> Result<()>,
    pub controllers: fn() -> Vec<Router<Container>>,
    pub route_docs: fn() -> Vec<RouteDocumentation>,
    pub on_module_init: fn() -> Vec<LifecycleHook>,
    pub on_module_destroy: fn() -> Vec<LifecycleHook>,
    pub on_application_bootstrap: fn() -> Vec<LifecycleHook>,
    pub on_application_shutdown: fn() -> Vec<LifecycleHook>,
    pub imports: fn() -> Vec<ModuleRef>,
    pub exports: fn() -> Vec<&'static str>,
    pub is_global: fn() -> bool,
}

impl ModuleRef {
    pub fn of<M: ModuleDefinition>() -> Self {
        Self {
            name: M::module_name(),
            register: M::register,
            controllers: M::controllers,
            route_docs: M::route_docs,
            on_module_init: M::on_module_init,
            on_module_destroy: M::on_module_destroy,
            on_application_bootstrap: M::on_application_bootstrap,
            on_application_shutdown: M::on_application_shutdown,
            imports: M::imports,
            exports: M::exports,
            is_global: M::is_global,
        }
    }
}

/*
ModuleDefinition = app module contract (manual for now)
*/
pub trait ModuleDefinition: Send + Sync + 'static {
    fn module_name() -> &'static str {
        std::any::type_name::<Self>()
    }

    fn register(container: &Container) -> Result<()>;

    fn imports() -> Vec<ModuleRef> {
        Vec::new()
    }

    fn is_global() -> bool {
        false
    }

    fn exports() -> Vec<&'static str> {
        Vec::new()
    }

    fn controllers() -> Vec<Router<Container>> {
        Vec::new()
    }

    fn route_docs() -> Vec<RouteDocumentation> {
        Vec::new()
    }

    fn on_module_init() -> Vec<LifecycleHook> {
        Vec::new()
    }

    fn on_module_destroy() -> Vec<LifecycleHook> {
        Vec::new()
    }

    fn on_application_bootstrap() -> Vec<LifecycleHook> {
        Vec::new()
    }

    fn on_application_shutdown() -> Vec<LifecycleHook> {
        Vec::new()
    }
}

pub struct InitializedModule {
    pub controllers: Vec<Router<Container>>,
    module_init_hooks: Vec<LifecycleHook>,
    module_destroy_hooks: Vec<LifecycleHook>,
    application_bootstrap_hooks: Vec<LifecycleHook>,
    application_shutdown_hooks: Vec<LifecycleHook>,
}

impl InitializedModule {
    pub fn run_module_init(&self, container: &Container) -> Result<()> {
        run_lifecycle_hooks("module_init", &self.module_init_hooks, container)
    }

    pub fn run_module_destroy(&self, container: &Container) -> Result<()> {
        run_lifecycle_hooks("module_destroy", &self.module_destroy_hooks, container)
    }

    pub fn run_application_bootstrap(&self, container: &Container) -> Result<()> {
        run_lifecycle_hooks(
            "application_bootstrap",
            &self.application_bootstrap_hooks,
            container,
        )
    }

    pub fn run_application_shutdown(&self, container: &Container) -> Result<()> {
        run_lifecycle_hooks(
            "application_shutdown",
            &self.application_shutdown_hooks,
            container,
        )
    }
}

pub fn initialize_module_runtime<M: ModuleDefinition>(container: &Container) -> Result<InitializedModule> {
    let mut state = ModuleGraphState::default();
    visit_module(ModuleRef::of::<M>(), container, &mut state)?;
    state.module_destroy_hooks.reverse();
    state.application_shutdown_hooks.reverse();
    Ok(InitializedModule {
        controllers: state.controllers,
        module_init_hooks: state.module_init_hooks,
        module_destroy_hooks: state.module_destroy_hooks,
        application_bootstrap_hooks: state.application_bootstrap_hooks,
        application_shutdown_hooks: state.application_shutdown_hooks,
    })
}

pub fn initialize_module_graph<M: ModuleDefinition>(
    container: &Container,
) -> Result<Vec<Router<Container>>> {
    Ok(initialize_module_runtime::<M>(container)?.controllers)
}

pub fn collect_module_route_docs<M: ModuleDefinition>() -> Result<Vec<RouteDocumentation>> {
    let mut state = DocumentationGraphState::default();
    visit_module_docs(ModuleRef::of::<M>(), &mut state)?;
    Ok(state.route_docs)
}

#[derive(Default)]
struct ModuleGraphState {
    visited: HashSet<&'static str>,
    visiting: HashSet<&'static str>,
    stack: Vec<&'static str>,
    controllers: Vec<Router<Container>>,
    module_init_hooks: Vec<LifecycleHook>,
    module_destroy_hooks: Vec<LifecycleHook>,
    application_bootstrap_hooks: Vec<LifecycleHook>,
    application_shutdown_hooks: Vec<LifecycleHook>,
    global_modules: HashSet<&'static str>,
}

#[derive(Default)]
struct DocumentationGraphState {
    visited: HashSet<&'static str>,
    visiting: HashSet<&'static str>,
    stack: Vec<&'static str>,
    route_docs: Vec<RouteDocumentation>,
}

fn visit_module(
    module: ModuleRef,
    container: &Container,
    state: &mut ModuleGraphState,
) -> Result<()> {
    if state.visited.contains(module.name) {
        return Ok(());
    }

    if state.visiting.contains(module.name) {
        let mut cycle = state.stack.clone();
        cycle.push(module.name);
        anyhow::bail!("Detected module import cycle: {}", cycle.join(" -> "));
    }

    state.visiting.insert(module.name);
    state.stack.push(module.name);
    framework_log_event(
        "module_register",
        &[("module", module.name.to_string())],
    );

    for imported in (module.imports)() {
        visit_module(imported, container, state)?;
    }

    (module.register)(container)
        .map_err(|err| anyhow::anyhow!("Failed to register module `{}`: {}", module.name, err))?;

    state.controllers.extend((module.controllers)());
    state.module_init_hooks.extend((module.on_module_init)());
    state.module_destroy_hooks.extend((module.on_module_destroy)());
    state
        .application_bootstrap_hooks
        .extend((module.on_application_bootstrap)());
    state
        .application_shutdown_hooks
        .extend((module.on_application_shutdown)());

    if (module.is_global)() {
        state.global_modules.insert(module.name);
    }

    for export in (module.exports)() {
        let is_registered = container.is_type_registered_name(export).map_err(|err| {
            anyhow::anyhow!(
                "Failed to verify exports for module `{}`: {}",
                module.name,
                err
            )
        })?;
        if !is_registered {
            anyhow::bail!(
                "Module `{}` exports `{}` but that provider is not registered in the container",
                module.name,
                export
            );
        }
    }

    state.stack.pop();
    state.visiting.remove(module.name);
    state.visited.insert(module.name);

    Ok(())
}

fn run_lifecycle_hooks(
    phase: &'static str,
    hooks: &[LifecycleHook],
    container: &Container,
) -> Result<()> {
    for hook in hooks {
        framework_log_event("lifecycle_hook_run", &[("phase", phase.to_string())]);
        hook(container)?;
    }

    Ok(())
}

fn visit_module_docs(module: ModuleRef, state: &mut DocumentationGraphState) -> Result<()> {
    if state.visited.contains(module.name) {
        return Ok(());
    }

    if state.visiting.contains(module.name) {
        let mut cycle = state.stack.clone();
        cycle.push(module.name);
        anyhow::bail!(
            "Detected module import cycle while collecting route docs: {}",
            cycle.join(" -> ")
        );
    }

    state.visiting.insert(module.name);
    state.stack.push(module.name);

    for imported in (module.imports)() {
        visit_module_docs(imported, state)?;
    }

    state.route_docs.extend((module.route_docs)());
    state.stack.pop();
    state.visiting.remove(module.name);
    state.visited.insert(module.name);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    struct ImportedConfig;
    struct AppService;

    struct ImportedModule;
    impl ModuleDefinition for ImportedModule {
        fn register(container: &Container) -> Result<()> {
            container.register(ImportedConfig)?;
            Ok(())
        }
    }

    struct AppModule;
    impl ModuleDefinition for AppModule {
        fn imports() -> Vec<ModuleRef> {
            vec![ModuleRef::of::<ImportedModule>()]
        }

        fn register(container: &Container) -> Result<()> {
            let imported = container.resolve::<ImportedConfig>()?;
            container.register(AppService::from(imported))?;
            Ok(())
        }
    }

    impl From<std::sync::Arc<ImportedConfig>> for AppService {
        fn from(_: std::sync::Arc<ImportedConfig>) -> Self {
            Self
        }
    }

    #[test]
    fn registers_imported_modules_before_local_providers() {
        let container = Container::new();
        let result = initialize_module_graph::<AppModule>(&container);

        assert!(result.is_ok(), "module graph registration should succeed");
        assert!(container.resolve::<ImportedConfig>().is_ok());
        assert!(container.resolve::<AppService>().is_ok());
    }

    struct SharedImportedModule;
    impl ModuleDefinition for SharedImportedModule {
        fn register(container: &Container) -> Result<()> {
            container.register(SharedMarker)?;
            Ok(())
        }
    }

    struct SharedMarker;
    struct LeftModule;
    struct RightModule;
    struct RootModule;

    impl ModuleDefinition for LeftModule {
        fn imports() -> Vec<ModuleRef> {
            vec![ModuleRef::of::<SharedImportedModule>()]
        }

        fn register(_container: &Container) -> Result<()> {
            Ok(())
        }
    }

    impl ModuleDefinition for RightModule {
        fn imports() -> Vec<ModuleRef> {
            vec![ModuleRef::of::<SharedImportedModule>()]
        }

        fn register(_container: &Container) -> Result<()> {
            Ok(())
        }
    }

    impl ModuleDefinition for RootModule {
        fn imports() -> Vec<ModuleRef> {
            vec![
                ModuleRef::of::<LeftModule>(),
                ModuleRef::of::<RightModule>(),
            ]
        }

        fn register(_container: &Container) -> Result<()> {
            Ok(())
        }
    }

    #[test]
    fn deduplicates_shared_imported_modules() {
        let container = Container::new();
        let result = initialize_module_graph::<RootModule>(&container);

        assert!(
            result.is_ok(),
            "shared imported modules should only register once"
        );
        assert!(container.resolve::<SharedMarker>().is_ok());
    }

    struct CycleA;
    struct CycleB;

    impl ModuleDefinition for CycleA {
        fn imports() -> Vec<ModuleRef> {
            vec![ModuleRef::of::<CycleB>()]
        }

        fn register(_container: &Container) -> Result<()> {
            Ok(())
        }
    }

    impl ModuleDefinition for CycleB {
        fn imports() -> Vec<ModuleRef> {
            vec![ModuleRef::of::<CycleA>()]
        }

        fn register(_container: &Container) -> Result<()> {
            Ok(())
        }
    }

    #[test]
    fn detects_module_import_cycles() {
        let container = Container::new();
        let err = initialize_module_graph::<CycleA>(&container).unwrap_err();

        assert!(
            err.to_string().contains("Detected module import cycle"),
            "error should include cycle detection message"
        );
    }

    struct MissingDependency;
    struct BrokenModule;

    impl ModuleDefinition for BrokenModule {
        fn register(container: &Container) -> Result<()> {
            let _ = container.resolve_in_module::<MissingDependency>(Self::module_name())?;
            Ok(())
        }
    }

    #[test]
    fn module_registration_error_includes_module_and_type_context() {
        let container = Container::new();
        let err = initialize_module_graph::<BrokenModule>(&container).unwrap_err();
        let message = err.to_string();

        assert!(message.contains("Failed to register module"));
        assert!(message.contains("BrokenModule"));
        assert!(message.contains("MissingDependency"));
    }

    #[derive(Clone)]
    struct HookLog(Arc<Mutex<Vec<&'static str>>>);

    fn push_hook(container: &Container, label: &'static str) -> Result<()> {
        let log = container.resolve::<HookLog>()?;
        log.0.lock().expect("hook log should be writable").push(label);
        Ok(())
    }

    fn hook_init(container: &Container) -> Result<()> {
        push_hook(container, "module_init")
    }

    fn hook_bootstrap(container: &Container) -> Result<()> {
        push_hook(container, "application_bootstrap")
    }

    fn hook_destroy(container: &Container) -> Result<()> {
        push_hook(container, "module_destroy")
    }

    fn hook_shutdown(container: &Container) -> Result<()> {
        push_hook(container, "application_shutdown")
    }

    struct HookModule;

    impl ModuleDefinition for HookModule {
        fn register(container: &Container) -> Result<()> {
            container.register(HookLog(Arc::new(Mutex::new(Vec::new()))))?;
            Ok(())
        }

        fn on_module_init() -> Vec<LifecycleHook> {
            vec![hook_init]
        }

        fn on_application_bootstrap() -> Vec<LifecycleHook> {
            vec![hook_bootstrap]
        }

        fn on_module_destroy() -> Vec<LifecycleHook> {
            vec![hook_destroy]
        }

        fn on_application_shutdown() -> Vec<LifecycleHook> {
            vec![hook_shutdown]
        }
    }

    #[test]
    fn initialized_runtime_runs_lifecycle_hooks_in_expected_order() {
        let container = Container::new();
        let runtime = initialize_module_runtime::<HookModule>(&container)
            .expect("module runtime should initialize");

        runtime
            .run_module_init(&container)
            .expect("module init hooks should run");
        runtime
            .run_application_bootstrap(&container)
            .expect("application bootstrap hooks should run");
        runtime
            .run_module_destroy(&container)
            .expect("module destroy hooks should run");
        runtime
            .run_application_shutdown(&container)
            .expect("application shutdown hooks should run");

        let log = container.resolve::<HookLog>().expect("hook log should resolve");
        let entries = log.0.lock().expect("hook log should be readable").clone();

        assert_eq!(
            entries,
            vec![
                "module_init",
                "application_bootstrap",
                "module_destroy",
                "application_shutdown"
            ]
        );
    }
}
